### ISSUE TITLE
URI must be a String, not Object

### ISSUE THREAD

**Issue by kenzierocks** [noamt/rest-gradle-plugin#17]
[This line](https://github.com/noamt/rest-gradle-plugin/blob/master/src/main/groovy/org/_10ne/gradle/rest/RestTask.groovy#L97) prevents URI from being an Object, as `StringUtil` requires a String. Could you call `toString` before that?

**Comment by noamt** [comment]
Will do!

**Comment by noamt** [comment]
I fixed this with 0.4.1. Note that due to new plugin ID restrictions I had to change the plugin ID

https://plugins.gradle.org/plugin/org.tenne.rest

**Comment by kenzierocks** [comment]
Thanks!
